config/routes.rb
Rails.application.routes.draw do
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles
  resources :working_experiences
  resources :collect_education_details
  resources :education_details
  
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :profile_image, :mobile, :email, :status)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :profile_image %>
    <%= form.text_field :profile_image %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Profile image</th>
      <th>Mobile</th>
      <th>Email</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.profile_image %></td>
        <td><%= profile.mobile %></td>
        <td><%= profile.email %></td>
        <td><%= profile.status %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Profile image:</strong>
  <%= @profile.profile_image %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @profile.mobile %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @profile.status %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>