config/routes.rb
Rails.application.routes.draw do
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles
  resources :working_experiences
  resources :collect_education_details
  resources :education_details
  
end

app/models/collect_education_detail.rb
class CollectEducationDetail < ApplicationRecord
end

app/controllers/collect_education_details_controller.rb
class CollectEducationDetailsController < ApplicationController
  before_action :set_collect_education_detail, only: %i[ show edit update destroy ]

  # GET /collect_education_details or /collect_education_details.json
  def index
    @collect_education_details = CollectEducationDetail.all
  end

  # GET /collect_education_details/1 or /collect_education_details/1.json
  def show
  end

  # GET /collect_education_details/new
  def new
    @collect_education_detail = CollectEducationDetail.new
  end

  # GET /collect_education_details/1/edit
  def edit
  end

  # POST /collect_education_details or /collect_education_details.json
  def create
    @collect_education_detail = CollectEducationDetail.new(collect_education_detail_params)

    respond_to do |format|
      if @collect_education_detail.save
        format.html { redirect_to @collect_education_detail, notice: "Collect education detail was successfully created." }
        format.json { render :show, status: :created, location: @collect_education_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collect_education_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collect_education_details/1 or /collect_education_details/1.json
  def update
    respond_to do |format|
      if @collect_education_detail.update(collect_education_detail_params)
        format.html { redirect_to @collect_education_detail, notice: "Collect education detail was successfully updated." }
        format.json { render :show, status: :ok, location: @collect_education_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collect_education_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collect_education_details/1 or /collect_education_details/1.json
  def destroy
    @collect_education_detail.destroy
    respond_to do |format|
      format.html { redirect_to collect_education_details_url, notice: "Collect education detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collect_education_detail
      @collect_education_detail = CollectEducationDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collect_education_detail_params
      params.require(:collect_education_detail).permit(:degree, :institute, :university, :year_of_passing, :percentage_CGPA, :edu_file_attachment)
    end
end

app/helpers/collect_education_details_helper.rb
module CollectEducationDetailsHelper
end

app/views/collect_education_details/_form.html.erb
<%= form_with(model: collect_education_detail, local: true) do |form| %>
  <% if collect_education_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collect_education_detail.errors.count, "error") %> prohibited this collect_education_detail from being saved:</h2>

      <ul>
      <% collect_education_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :degree %>
    <%= form.text_field :degree %>
  </div>

  <div class="field">
    <%= form.label :institute %>
    <%= form.text_field :institute %>
  </div>

  <div class="field">
    <%= form.label :university %>
    <%= form.text_field :university %>
  </div>

  <div class="field">
    <%= form.label :year_of_passing %>
    <%= form.text_field :year_of_passing %>
  </div>

  <div class="field">
    <%= form.label :percentage_CGPA %>
    <%= form.text_field :percentage_CGPA %>
  </div>

  <div class="field">
    <%= form.label :edu_file_attachment %>
    <%= form.text_field :edu_file_attachment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collect_education_details/edit.html.erb
<h1>Editing Collect Education Detail</h1>

<%= render 'form', collect_education_detail: @collect_education_detail %>

<%= link_to 'Show', @collect_education_detail %> |
<%= link_to 'Back', collect_education_details_path %>

app/views/collect_education_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collect Education Details</h1>

<table>
  <thead>
    <tr>
      <th>Degree</th>
      <th>Institute</th>
      <th>University</th>
      <th>Year of passing</th>
      <th>Percentage cgpa</th>
      <th>Edu file attachment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collect_education_details.each do |collect_education_detail| %>
      <tr>
        <td><%= collect_education_detail.degree %></td>
        <td><%= collect_education_detail.institute %></td>
        <td><%= collect_education_detail.university %></td>
        <td><%= collect_education_detail.year_of_passing %></td>
        <td><%= collect_education_detail.percentage_CGPA %></td>
        <td><%= collect_education_detail.edu_file_attachment %></td>
        <td><%= link_to 'Show', collect_education_detail %></td>
        <td><%= link_to 'Edit', edit_collect_education_detail_path(collect_education_detail) %></td>
        <td><%= link_to 'Destroy', collect_education_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collect Education Detail', new_collect_education_detail_path %>

app/views/collect_education_details/new.html.erb
<h1>New Collect Education Detail</h1>

<%= render 'form', collect_education_detail: @collect_education_detail %>

<%= link_to 'Back', collect_education_details_path %>

app/views/collect_education_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Degree:</strong>
  <%= @collect_education_detail.degree %>
</p>

<p>
  <strong>Institute:</strong>
  <%= @collect_education_detail.institute %>
</p>

<p>
  <strong>University:</strong>
  <%= @collect_education_detail.university %>
</p>

<p>
  <strong>Year of passing:</strong>
  <%= @collect_education_detail.year_of_passing %>
</p>

<p>
  <strong>Percentage cgpa:</strong>
  <%= @collect_education_detail.percentage_CGPA %>
</p>

<p>
  <strong>Edu file attachment:</strong>
  <%= @collect_education_detail.edu_file_attachment %>
</p>

<%= link_to 'Edit', edit_collect_education_detail_path(@collect_education_detail) %> |
<%= link_to 'Back', collect_education_details_path %>