config/routes.rb
Rails.application.routes.draw do
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles
  resources :working_experiences
  resources :collect_education_details
  resources :education_details
  
end

app/models/working_experience.rb
class WorkingExperience < ApplicationRecord
  mount_uploader :exp_file_upload, AttachmentUploader # Tells rails to use this uploader for this model.   
  validates :company_name, presence: true # Make sure the owner's name is present. 
end

app/controllers/working_experiences_controller.rb
class WorkingExperiencesController < ApplicationController
  before_action :set_working_experience, only: %i[ show edit update destroy ]

  # GET /working_experiences or /working_experiences.json
  def index
    @working_experiences = WorkingExperience.all
  end

  # GET /working_experiences/1 or /working_experiences/1.json
  def show
  end

  # GET /working_experiences/new
  def new
    @working_experience = WorkingExperience.new
  end

  # GET /working_experiences/1/edit
  def edit
  end

  # POST /working_experiences or /working_experiences.json
  def create
    @working_experience = WorkingExperience.new(working_experience_params)

    respond_to do |format|
      if @working_experience.save
        format.html { redirect_to @working_experience, notice: "Working experience was successfully created." }
        format.json { render :show, status: :created, location: @working_experience }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @working_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /working_experiences/1 or /working_experiences/1.json
  def update
    respond_to do |format|
      if @working_experience.update(working_experience_params)
        format.html { redirect_to @working_experience, notice: "Working experience was successfully updated." }
        format.json { render :show, status: :ok, location: @working_experience }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @working_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /working_experiences/1 or /working_experiences/1.json
  def destroy
    @working_experience.destroy
    respond_to do |format|
      format.html { redirect_to working_experiences_url, notice: "Working experience was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_working_experience
      @working_experience = WorkingExperience.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def working_experience_params
      params.require(:working_experience).permit(:company_name, :designation, :from_date, :to_date, :duration, :exp_file_upload)
    end
end

app/helpers/working_experiences_helper.rb
module WorkingExperiencesHelper
end

app/views/working_experiences/_form.html.erb
<%= form_with(model: working_experience, local: true) do |form| %>
  <% if working_experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(working_experience.errors.count, "error") %> prohibited this working_experience from being saved:</h2>

      <ul>
      <% working_experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :designation %>
    <%= form.text_field :designation %>
  </div>

  <div class="field">
    <%= form.label :from_date %>
    <%= form.text_field :from_date %>
  </div>

  <div class="field">
    <%= form.label :to_date %>
    <%= form.text_field :to_date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="field">
    <%= form.label :exp_file_upload %>
    <%= form.file_field :exp_file_upload %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/working_experiences/edit.html.erb
<h1>Editing Working Experience</h1>

<%= render 'form', working_experience: @working_experience %>

<%= link_to 'Show', @working_experience %> |
<%= link_to 'Back', working_experiences_path %>

app/views/working_experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Working Experiences</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Designation</th>
      <th>From date</th>
      <th>To date</th>
      <th>Duration</th>
      <th>Exp file upload</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @working_experiences.each do |working_experience| %>
      <tr>
        <td><%= working_experience.company_name %></td>
        <td><%= working_experience.designation %></td>
        <td><%= working_experience.from_date %></td>
        <td><%= working_experience.to_date %></td>
        <td><%= working_experience.duration %></td>
        <td><%= working_experience.exp_file_upload %></td>
        <td><%= link_to 'Show', working_experience %></td>
        <td><%= link_to 'Edit', edit_working_experience_path(working_experience) %></td>
        <td><%= link_to 'Destroy', working_experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Working Experience', new_working_experience_path %>

app/views/working_experiences/new.html.erb
<h1>New Working Experience</h1>

<%= render 'form', working_experience: @working_experience %>

<%= link_to 'Back', working_experiences_path %>

app/views/working_experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @working_experience.company_name %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @working_experience.designation %>
</p>

<p>
  <strong>From date:</strong>
  <%= @working_experience.from_date %>
</p>

<p>
  <strong>To date:</strong>
  <%= @working_experience.to_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @working_experience.duration %>
</p>

<p>
  <strong>Exp file upload:</strong>
  <%= @working_experience.exp_file_upload %>
</p>

<%= link_to 'Edit', edit_working_experience_path(@working_experience) %> |
<%= link_to 'Back', working_experiences_path %>