config/routes.rb
Rails.application.routes.draw do
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles
  resources :working_experiences
  resources :collect_education_details
  resources :education_details
  
end

app/models/education_detail.rb
class EducationDetail < ApplicationRecord
  mount_uploader :edu_file_attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
  validates :degree, presence: true # Make sure the owner's name is present. 
end

app/controllers/education_details_controller.rb
class EducationDetailsController < ApplicationController
  before_action :set_education_detail, only: %i[ show edit update destroy ]

  # GET /education_details or /education_details.json
  def index
    @education_details = EducationDetail.all
  end

  # GET /education_details/1 or /education_details/1.json
  def show
  end

  # GET /education_details/new
  def new
    @education_detail = EducationDetail.new
  end

  # GET /education_details/1/edit
  def edit
  end

  # POST /education_details or /education_details.json
  def create
    @education_detail = EducationDetail.new(education_detail_params)

    respond_to do |format|
      if @education_detail.save
        format.html { redirect_to @education_detail, notice: "Education detail was successfully created." }
        format.json { render :show, status: :created, location: @education_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @education_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /education_details/1 or /education_details/1.json
  def update
    respond_to do |format|
      if @education_detail.update(education_detail_params)
        format.html { redirect_to @education_detail, notice: "Education detail was successfully updated." }
        format.json { render :show, status: :ok, location: @education_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @education_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /education_details/1 or /education_details/1.json
  def destroy
    @education_detail.destroy
    respond_to do |format|
      format.html { redirect_to education_details_url, notice: "Education detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education_detail
      @education_detail = EducationDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def education_detail_params
      params.require(:education_detail).permit(:degree, :institute, :university, :year_of_passing, :percentage_CGPA, :edu_file_attachment)
    end
end

app/helpers/education_details_helper.rb
module EducationDetailsHelper
end

app/views/education_details/_form.html.erb
<%= form_with(model: education_detail, local: true) do |form| %>
  <% if education_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(education_detail.errors.count, "error") %> prohibited this education_detail from being saved:</h2>

      <ul>
      <% education_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :degree %>
    <%= form.text_field :degree %>
  </div>

  <div class="field">
    <%= form.label :institute %>
    <%= form.text_field :institute %>
  </div>

  <div class="field">
    <%= form.label :university %>
    <%= form.text_field :university %>
  </div>

  <div class="field">
    <%= form.label :year_of_passing %>
    <%= form.text_field :year_of_passing %>
  </div>

  <div class="field">
    <%= form.label :percentage_CGPA %>
    <%= form.text_field :percentage_CGPA %>
  </div> 

  <div class="field">
    <%= form.label :edu_file_attachment %>
    <%= form.file_field :edu_file_attachment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/education_details/edit.html.erb
<h1>Editing Education Detail</h1>

<%= render 'form', education_detail: @education_detail %>

<%= link_to 'Show', @education_detail %> |
<%= link_to 'Back', education_details_path %>

app/views/education_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Education Details</h1>

<table>
  <thead>
    <tr>
      <th>Degree</th>
      <th>Institute</th>
      <th>University</th>
      <th>Year of passing</th>
      <th>Percentage cgpa</th>
      <th>Edu file attachment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @education_details.each do |education_detail| %>
      <tr>
        <td><%= education_detail.degree %></td>
        <td><%= education_detail.institute %></td>
        <td><%= education_detail.university %></td>
        <td><%= education_detail.year_of_passing %></td>
        <td><%= education_detail.percentage_CGPA %></td>
        <td><%= education_detail.edu_file_attachment %></td>
        <td><%= link_to 'Show', education_detail %></td>
        <td><%= link_to 'Edit', edit_education_detail_path(education_detail) %></td>
        <td><%= link_to 'Destroy', education_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education Detail', new_education_detail_path %>

app/views/education_details/new.html.erb
<h1>New Education Detail</h1>

<%= render 'form', education_detail: @education_detail %>

<%= link_to 'Back', education_details_path %>

app/views/education_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Degree:</strong>
  <%= @education_detail.degree %>
</p>

<p>
  <strong>Institute:</strong>
  <%= @education_detail.institute %>
</p>

<p>
  <strong>University:</strong>
  <%= @education_detail.university %>
</p>

<p>
  <strong>Year of passing:</strong>
  <%= @education_detail.year_of_passing %>
</p>

<p>
  <strong>Percentage cgpa:</strong>
  <%= @education_detail.percentage_CGPA %>
</p>

<p>
  <strong>Edu file attachment:</strong>
  <%= @education_detail.edu_file_attachment %>
</p>

<%= link_to 'Edit', edit_education_detail_path(@education_detail) %> |
<%= link_to 'Back', education_details_path %>